* Plano do Projeto Experimental

** Máquinas

Quais máquinas iremos executar?

| Máquina   | Processador                      | Threads | Cores | Frequência |
|-----------+----------------------------------+---------+-------+------------|
| draco     | 2 x Intel(R) Xeon(R) E5-2640 v2  |      32 |    16 | 2.0 GH     |
| poti      | Intel(R) Core(TM) i7-14700KF     |      28 |    20 | 3.4 GHz    |
| cei       | 2 x Intel(R) Xeon(R) Silver 4116 |      48 |    24 | 2.1 GHz    |
| grace     | 2 x Grace A02                    |     144 |   144 | 3.4 GHz    |
| tupi[3-6] | Intel(R) Core(TM) i9-14900KF     |      32 |    24 | 3.2 GHz    |


O plano é executar experimentos em todas essas máquinas.

** Parâmetros

Quais parâmetros queremos analisar nos testes.
Iniciamos um teste com um volume fixo -> 576? Muito grande para a CPU talvez
- Para esse teste, computamos com e sem IO 
	- Com IO consideramos o mkspan -> preciso instrumentar isso ainda
	- Sem IO consideramos os Msamples
	- Nisso temos um teste muito semelhante ao do /ideal-seg/, 
	  em que também fixamos o número de iterações e alteramos a segmentação do meio, com várias replicações.

Temos outro teste que consiste em manter a ordem fixa (tamanho do bloco) e mudar o volume.
- Podemos usar o mesmo setup de escalonadores, dessa vez sem IO para considerar bem os Msamples.
- Só precisamos de um tamanho de bloco não tão grande, que dê uma granularidade legal.
- Comparamos a execução com os tamanhos do /fletcher-base/.

*** Usar escalonadores do StarPU

Selecionar alguns.
  |--------+----------------------------------------------------+-------------|
  | name   | descriptor                                         | performance |
  |--------+----------------------------------------------------+-------------|
  | random | random                                             | no          |
  | ws     | worker rouba a task de outro caso este esteja idle | no          |
  | lws    | tipo ws, mas local                                 | no          |
  | dm     | usa tempo de execução                              | yes         |
  | dmdar  | tipo dmda, mas considera o local                   | yes         |

Não estamos incluindo outros escalonadores que levam em consideração a prioridade das tasks,
pois estes são desnecessários. O star-fletcher é dominado por uma única task.

** Experimentos

Temos que gerar 5 experimentos
 - Experimento volume fixo
	- Versão star-fletcher
	- Versão fletcher-base
	- Dado o resultado deste experimentos, fazer o de baixo
 - Experimento ordem fixa
	- Versão star-fletcher
	- Versão fletcher-base
 - Geração de traces do star-fletcher

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  library(DoE.base)
  library(glue)
  library(tidyverse)
  library(numbers)

  #no scientific notation
  options(scipen = 999)


  total_width = 384
  border_size = 4
  absorb_size = 8
  width = total_width - 2 * (border_size + absorb_size)
  seed = 0
  time_step = 0.0001
  iterations = 10
  replications = 5

  generate_experiment <- function(factors, replications, seed) {
    DoE.base::fac.design(
      nfactors = length(factors),
      replications = replications,
      repeat.only = FALSE,
      randomize = TRUE,
      seed = seed,
      nlevels = sapply(factors, length),
      factor.names = factors
    )
  }

  segmentations = divisors(total_width)

  sf_cpu_factors <- list(
    WithIO =  c(0, 1),
    BlockSeg = segmentations[segmentations > 3 & segmentations <= (total_width / 9)],
    Schedulers = c("random", "ws", "lws", "dm", "dmdar")
  )

  sf_ex <- generate_experiment(sf_cpu_factors, replications, seed) |>
    as_tibble() |>
    mutate(
  	Width = width,
  	AbsorbSize = absorb_size,
  	TotalTime = format(time_step * iterations, scientific = FALSE),
  	TimeStep = format(time_step, scientific = FALSE),
  	OutputTime = format(time_step, scientific = FALSE)
    )
  # for the fletcher-base, remove all non-relevant parameters
  fb_ex <- sf_ex |> select(-BlockSeg, -Schedulers) |> unique()


  # for the traces, remove the replications and select a smaller range of segmentaions
  # TODO: sf_ex_traces

  #print(dim(fb_ex))

  sf_ex |> readr::write_csv(glue("./sscad/star-fletcher-fix-size.csv"))
  fb_ex |> readr::write_csv(glue("./sscad/fletcher-base-fix-size.csv"))

  traces <- sf_ex |>
    select(-Blocks) |>
    unique() |>
    filter(Schedulers == "lws" | Schedulers == "dmdar") |>
    filter(as.numeric(as.character(BlockSeg)) > 8)

  traces |> readr::write_csv(glue("./sscad/star-fletcher-fix-size-traces.csv"))

#+END_SRC

Experimento para o star-fletcher e fletcher base para verificar como o aumento do
tamanho afeta o tempo de execução. O uso de uma ordem fixa também mostrar como
o tamanho ideal do bloco pode mudar com diferentes tamanhos de volume.

O melhor tamanho atualmente encontrado é ordem 64. Com um tamanho de 384, temos que
a segmentação ideal é 6 -> 216 blocos por iteração.

Consideramos uma ordem menor, 32, para ter uma maior granularidade.

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  fixed_order = 32

  sf_cpu_size_grow <- list(
    WithIO = c(0, 1),
    BlockSeg = c(3, 5, 7,  9, 11, 13),
    Schedulers = c("random", "ws", "lws", "dm", "dmdar")
  )

  sf_ex_order <- generate_experiment(sf_cpu_size_grow, replications, seed) |>
    as_tibble() |>
    mutate(
  	Width = ((as.numeric(as.character(BlockSeg)) * fixed_order) - (2 * (border_size + absorb_size))),
  	AbsorbSize = absorb_size,
  	TotalTime = format(time_step * iterations, scientific = FALSE),
  	TimeStep = format(time_step, scientific = FALSE),
  	OutputTime = format(time_step, scientific = FALSE)
    )

  fb_ex_order <- sf_ex_order |> select(-BlockSeg, -Schedulers) |> unique()

  sf_ex_order |> readr::write_csv(glue("./sscad/star-fletcher-fix-order.csv"))
  fb_ex_order |> readr::write_csv(glue("./sscad/fletcher-base-fix-order.csv"))

#+END_SRC

Os resultados observados não foram ideais, principalmente a considerar a máquina grace.
Nisso, vamos aumentar a ordem para 64 e relançar os experimentos.

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  fixed_order = 64

  sf_cpu_size_grow <- list(
    WithIO = c(0, 1),
    BlockSeg = c(3, 4, 5, 6, 7),
    Schedulers = c("ws", "lws", "dm", "dmdar")
  )

  sf_ex_order <- generate_experiment(sf_cpu_size_grow, replications, seed) |>
    as_tibble() |>
    mutate(
  	Width = ((as.numeric(as.character(BlockSeg)) * fixed_order) - (2 * (border_size + absorb_size))),
  	AbsorbSize = absorb_size,
  	TotalTime = format(time_step * iterations, scientific = FALSE),
  	TimeStep = format(time_step, scientific = FALSE),
  	OutputTime = format(time_step, scientific = FALSE)
    )

  fb_ex_order <- sf_ex_order |> select(-BlockSeg, -Schedulers) |> unique()

  sf_ex_order |> readr::write_csv(glue("./sscad/star-fletcher-fix-order-64.csv"))
  fb_ex_order |> readr::write_csv(glue("./sscad/fletcher-base-fix-order-64.csv"))
#+END_SRC


* Análise de Dados

Aqui segue os dados das máquinas usadas nas execuções. 

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  options(crayon.enabled = FALSE)
  #library(starvz)
  library(tidyverse)
  library(ggplot2)
  library(dplyr)
  library(patchwork)

  base_dir = "./sscad/results"

  machines <- tribble(
    ~Machine, ~Processor, ~Ghz, ~Threads, ~Cores, 
    "tupi3", "Intel(R) Core(TM) i9-14900KF", 3.2, 32, 24,
    "tupi4", "Intel(R) Core(TM) i9-14900KF", 3.2, 32, 24,
    "poti4", "Intel(R) Core(TM) i7-14700KF", 3.4, 28, 20,
    "poti5", "Intel(R) Core(TM) i7-14700KF", 3.4, 28, 20,
    "grace1", "2 x Grace A02", 3.4, 144, 144,
    "cei1", "2 x Intel(R) Xeon(R) Silver 4116", 2.1, 48, 24,
    "cei2", "2 x Intel(R) Xeon(R) Silver 4116", 2.1, 48, 24,
    "cei3", "2 x Intel(R) Xeon(R) Silver 4116", 2.1, 48, 24,
    "draco1", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16,
    "draco2", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16,
    "draco6", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16,
    "draco7", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16
  )

#+END_SRC


** Experimentos base da Variação da Ordem

Experimento do star-fletcher

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  ex_star_fletcher <- read_csv('./sscad/star-fletcher-fix-size.csv')
  sf <- machines |> cross_join(ex_star_fletcher)

  sf_res <- sf |>
    mutate(FILE = paste0(base_dir,"/star-fletcher-cpu/", Machine ,"/stdout-", Schedulers, "-", BlockSeg, "-", WithIO, "-", substring(1, Blocks), ".out")) |>
    mutate(Data = map(FILE, function(file) {
      if(!dir.exists(dirname(file))){
        return(NULL)
      }
      #print(file)
      lines <- tryCatch({
        read_lines(file)
      }, error = function(e){
        message(paste0("Warning: Failed to read file: ", file, ". Skipping..."))
        return(NULL) # Returns NULL instead of breaking the script
      })
      if(is.null(lines)) {
        return(NULL)
      }
      vals <- lines |>  map(\(l) as.numeric(str_extract(l, " \\d+.\\d+")))
      tribble(~Msamples, ~ExecTime, 
              vals[[6]], vals[[5]])
    })) |>
    filter(lengths(Data) > 0) |>
    unnest(Data) |>
    mutate(Order = (Width + 2 * (AbsorbSize + 4)) / BlockSeg) 
#+END_SRC

Experimento do fletcher-base

#+BEGIN_SRC R :session *R* :async yes :results output silent 

  ex_fletcher_base <- read_csv('./sscad/fletcher-base-fix-size.csv')
  fb <- machines |> cross_join(ex_fletcher_base)

  fb_res <- fb |>
    mutate(FILE = paste0(base_dir, "/fletcher-base-cpu/", Machine ,"/stdout-",  WithIO, "-", substring(1, Blocks), ".out")) |>
    mutate(Data = map(FILE, function(file) {
      if(!dir.exists(dirname(file))){
        return(NULL)
      }
      
       lines <- tryCatch({
   	read_lines(file) 
       }, error = function(e){
   	 message(paste0("Warning: Failed to read file: ", file, ". Skipping..."))
         return(NULL) # Returns NULL instead of breaking the script
       })
       if(is.null(lines)) {
         return(NULL)
       }
       msamples <-  lines |>
        str_subset("MSamples/s") |> 
        str_extract("\\d+.\\d+") |> 
        as.numeric()


       exec_time <-  lines |>
        str_subset("Total execution time") |> 
        str_extract("\\d+.\\d+") |> 
        as.numeric()

       tribble(~Msamples, ~ExecTime,
               msamples[1], exec_time[1])
    })) |>
    filter(lengths(Data) > 0) |>
    unnest(Data) 

#+END_SRC

*** Gráficos dos resultados

Gráfico da relação Mega Samples por Tamanho de bloco.
Pode-se observar que quando desconsiderando o IO, para os
escalonadores simples (lws e ws) há um ponto em que a performance do star-fletcher supera o
obtido no fletcher-base.
Quando observando essa métrica considerando o IO, a única máquina que mantém essa vantagem é a poti.
Entretanto, a comparação quando o IO está ligado é injusta, pois a conta do Msamples no flecher-base desconsidera o tempo de IO,
enqunato essa granularidade é não é possível no caso do star-fletcher devido a sua arquitetura em tarefas. 

#+BEGIN_SRC R :session *R* :async yes :results output silent

  x_breaks <- sort(unique(sf_res$Order))
  msamples_plot <- function(io_state) {
    max_fb <- fb_res |>
      mutate(Machine = str_sub(Machine, end = -2)) |>
  	filter(WithIO == io_state) |>
  	group_by(Machine) |>
  	summarize(Max_Msamples = max(Msamples, na.rm = TRUE), Min_Msamples = min(Msamples, na.rm = TRUE), .groups = "drop") #|>
  	# Join back to machines so the hline can inherit the exact Machine color
  	#left_join(machines |> select(Machine, Processor), by = "Processor")

   sf_msamples_plot <- sf_res |>
     filter(WithIO == io_state) |>
     mutate(Machine = str_sub(Machine, end = -2))

    ggplot(sf_msamples_plot, aes(x = Order, y = Msamples, color = Machine)) +
    geom_point(size = 2, alpha = 0.3) +
    geom_line(linewidth = 0.8) +
    geom_hline(data = max_fb, aes(yintercept = Max_Msamples, color = Machine), linetype = "dashed", linewidth = 0.8) +
    scale_x_continuous(breaks = x_breaks) +
    ylim(0,NA)+
    facet_grid(~ Schedulers) + 
    labs(
  	title = paste0("Msamples vs. Block Order with WithIO = ", io_state),
  	subtitle = "Faceted by Scheduler",
  	x = "Block Size",
  	y = "Msamples/s"
    ) +
    theme_bw(base_size=15) +
    theme(legend.position = "bottom")
  }

  msamples_plot(0) / msamples_plot(1)
#+END_SRC

Gráfico de tempo de execução por tamanho do bloco.
Pode-se observar, que quando considerando o tempo de execução (que considera o tempo de IO junto),
todas as máquinas possuem um ponto em que o star-fletcher teve um desempenho melhor que o fletcher-base.
É interessante observar que no caso da grace, isso só acontece em uma configuração específica usando o escalonador ws.
Mesmo assim, os outros escalonadores também se aproximam desse resultado ao chegar mais perto da segmentação ideal.

#+BEGIN_SRC R :session *R* :async yes :results output silent

  x_breaks <- sort(unique(sf_res$Order))

  time_plot <- function(io_state) {
    max_fb_time <- fb_res |>
      mutate(Machine = str_sub(Machine, end = -2)) |>
  	filter(WithIO == io_state) |>
  	group_by(Machine) |>
  	summarize(Max_Time = max(ExecTime, na.rm = TRUE), Min_Time = min(ExecTime, na.rm = TRUE), .groups = "drop") #|>
  	# Join back to machines so the hline can inherit the exact Machine color
  	#left_join(machines |> select(Machine, Processor), by = "Processor")

   sf_time_plot <- sf_res |>
     filter(WithIO == io_state) |>
     mutate(Machine = str_sub(Machine, end = -2))

    ggplot(sf_time_plot, aes(x = factor(Order), y = ExecTime, fill = Machine)) +
    stat_summary(fun = mean, geom = "bar", position = "dodge", color = "black", linewidth = 0.3) +
    # geom_jitter() +
    geom_hline(data = max_fb_time, aes(yintercept = Min_Time), linewidth = 0.8) +
    #scale_y_continuous(breaks = sort(unique(c(seq(0, 50, by = 10), max_fb_time$Min_Time))), labels = function(x) round(x, 2), # Rounds to 2 decimal places to keep it tidy) +
    #scale_x_continuous(breaks = x_breaks) +
    coord_cartesian(ylim = c(0, 40)) +
    #ylim(0,50)+
    facet_grid(Machine ~ Schedulers) + 
    labs(
  	title = paste0("Execution Time vs. Block Order with WithIO = ", io_state) ,
  	subtitle = "Faceted by Scheduler",
  	x = "Block Size",
  	y = "Execution Time (s)"
    ) +
    theme_bw(base_size=15) +
    theme(legend.position = "bottom")
    }

  #time_plot(0)

  time_plot(1)
    
#+END_SRC

** Experimentos de Ordem fixa, variando o tamanho

Extraindo os dados dos experimentos do star-fletcher-fix-order

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  ex_star_fletcher_order  <- read_csv('./sscad/star-fletcher-fix-order.csv')
  sf_order <- machines |> cross_join(ex_star_fletcher_order)

  sf_res_order <- sf_order |>
    mutate(FILE = paste0(base_dir,"/star-fletcher-cpu-fix-order/", Machine ,"/stdout-", Schedulers, "-", BlockSeg, "-", WithIO, "-", substring(1, Blocks), ".out")) |>
    mutate(Data = map(FILE, function(file) {
      if(!dir.exists(dirname(file))){
        return(NULL)
      }
      
      lines <- tryCatch({
        read_lines(file)
      }, error = function(e){
        message(paste0("Warning: Failed to read file: ", file, ". Skipping..."))
        return(NULL) # Returns NULL instead of breaking the script
      })
      if(is.null(lines)) {
        return(NULL)
      }
      vals <- lines |>  map(\(l) as.numeric(str_extract(l, " \\d+.\\d+")))
      tribble(~Msamples, ~ExecTime, 
              vals[[6]], vals[[5]])
    })) |>
    filter(lengths(Data) > 0) |>
    unnest(Data)
#+END_SRC

Extraindo os dados dos experimentos do star-fletcher-fix-order-64

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  ex_star_fletcher_order  <- read_csv('./sscad/star-fletcher-fix-order-64.csv')
  sf_order <- machines |> cross_join(ex_star_fletcher_order)

  sf_res_order <- sf_order |>
    mutate(FILE = paste0(base_dir,"/star-fletcher-cpu-fix-order-64/", Machine ,"/stdout-", Schedulers, "-", BlockSeg, "-", WithIO, "-", substring(1, Blocks), ".out")) |>
    mutate(Data = map(FILE, function(file) {
      if(!dir.exists(dirname(file))){
        return(NULL)
      }
      
      lines <- tryCatch({
        read_lines(file)
      }, error = function(e){
        message(paste0("Warning: Failed to read file: ", file, ". Skipping..."))
        return(NULL) # Returns NULL instead of breaking the script
      })
      if(is.null(lines)) {
        return(NULL)
      }
      vals <- lines |>  map(\(l) as.numeric(str_extract(l, " \\d+.\\d+")))
      tribble(~Msamples, ~ExecTime, 
              vals[[6]], vals[[5]])
    })) |>
    filter(lengths(Data) > 0) |>
    unnest(Data)
#+END_SRC


Experimento do fletcher-base-fix-order

#+BEGIN_SRC R :session *R* :async yes :results output silent 

  ex_fletcher_base_order <- read_csv('./sscad/fletcher-base-fix-order.csv')
  fb_order <- machines |> cross_join(ex_fletcher_base_order)

  fb_res_order <- fb_order |>
    mutate(FILE = paste0(base_dir, "/fletcher-base-cpu-fix-order/", Machine ,"/stdout-", Width, "-", WithIO, "-", substring(1, Blocks), ".out")) |>
    mutate(Data = map(FILE, function(file) {
      if(!dir.exists(dirname(file))){
        return(NULL)
      }
      
       lines <- tryCatch({
   	read_lines(file) 
       }, error = function(e){
   	 message(paste0("Warning: Failed to read file: ", file, ". Skipping..."))
         return(NULL) # Returns NULL instead of breaking the script
       })
       if(is.null(lines)) {
         return(NULL)
       }
       msamples <-  lines |>
        str_subset("MSamples/s") |> 
        str_extract("\\d+.\\d+") |> 
        as.numeric()

       exec_time <-  lines |>
        str_subset("Total execution time") |> 
        str_extract("\\d+.\\d+") |> 
        as.numeric()

       tribble(~Msamples, ~ExecTime,
               msamples[1], exec_time[1])
    })) |>
    filter(lengths(Data) > 0) |>
    unnest(Data)
#+END_SRC

*** Gráficos


Gráficos do aumento do tamanho pelos Msamples

#+BEGIN_SRC R :session *R* :async yes :results output silent

  x_breaks <- sort(unique(sf_res_order$Width))
  msamples_plot <- function(io_state) {
    fb_msamples <- fb_res_order |>
      mutate(Machine = str_sub(Machine, end = -2)) |>
      filter(WithIO == io_state)

   sf_msamples_order_plot <- sf_res_order |>
     filter(WithIO == io_state) |>
     mutate(Machine = str_sub(Machine, end = -2))

    ggplot(sf_msamples_order_plot, aes(x = Width, y = Msamples, color = Machine)) +
    geom_point() +
    geom_line(linewidth = 0.8) +
    stat_summary(data = fb_msamples, fun = mean, geom = "line",  linetype = "dotted", linewidth = 0.8) +
    #geom_hline(data = max_fb, aes(yintercept = Max_Msamples, color = Machine), linetype = "dashed", linewidth = 0.8) +
    scale_x_continuous(breaks = x_breaks) +
    #ylim(0,NA)+
    facet_grid(Machine ~ Schedulers) + 
    labs(
  	title = paste0("Msamples vs. Volume Size with WithIO = ", io_state),
  	subtitle = "Faceted by Scheduler",
  	x = "Block Size",
  	y = "Msamples/s"
    ) +
    theme_bw(base_size=15) +
    theme(legend.position = "bottom")
  }

  msamples_plot(0) #/ msamples_plot(1)
#+END_SRC

Gráficos do aumento do tamanho pelo tempo de execução

#+BEGIN_SRC R :session *R* :async yes :results output silent

  x_breaks <- sort(unique(sf_res_order$Width))
  msamples_plot <- function(io_state) {
    fb_msamples <- fb_res_order |>
      mutate(Machine = str_sub(Machine, end = -2)) |>
      filter(WithIO == io_state)

   sf_msamples_order_plot <- sf_res_order |>
     filter(WithIO == io_state) |>
     mutate(Machine = str_sub(Machine, end = -2))

    ggplot(sf_msamples_order_plot, aes(x = Width, y = ExecTime, color = Machine)) +
    geom_point() +
    geom_line(linewidth = 0.8) +
    stat_summary(data = fb_msamples, fun = mean, geom = "line",  linetype = "dotted", linewidth = 1) +
    #geom_hline(data = max_fb, aes(yintercept = Max_Msamples, color = Machine), linetype = "dashed", linewidth = 0.8) +
    scale_x_continuous(breaks = x_breaks) +
    #ylim(0,NA)+
    facet_grid(Machine ~ Schedulers) + 
    labs(
  	title = paste0("Execution Time vs. Volume Size with WithIO = ", io_state),
  	subtitle = "Faceted by Scheduler",
  	x = "Block Size",
  	y = "Time (s)"
    ) +
    theme_bw(base_size=15) +
    theme(legend.position = "bottom")
  }

  msamples_plot(1) #/ msamples_plot(1)
#+END_SRC
