* Plano do Projeto Experimental


** Versões

Temos três versões do Fletcher para comparar com:
- fletcher-base
  - Single Node
- fletcher-riggon
  - Single Node
  - Multi GPU
- fletcher-spadotto
  - Multi nodo
  - Usa MPI

As análises precisam ser comparativas com essas 3 implementações.
Mesmo a versão base e a do Riggon serem similares em relação a máquinas com uma GPU,
é necessário testar nas duas as implementações.

** Máquinas

| Máquina | Nº GPUS | Local         |
|---------|---------|---------------|
| grace   |       1 | PCAD          |
| cidia   |       2 | PCAD          |
| tupi    |       1 | PCAD          |
| poti    |       1 | PCAD          |
| saude   |       3 | PCAD          |
| xh3000  |       4 | Santos Dumond |
| H100_dx |       4 | Santos Dumond |

O plano é executar experimentos em todas essas máquinas.


** Parâmetros

Precisamos fixar o maior tamanho possível de meio para as execuções.
Se não me engano, o /fletcher-base/ tem uma limitação de tamanho de 600 x 600 x 600,
mas precisamos de um experimento que demonstre isso.
(ou não, talvez só tentar execuções incrementais até o crash seria suficiente).
Cada máquina tem uma configuração ideal de segmentação.
Precisamos montar um projeto experimental para determinar isso. Nele temos:
- Um tamanho de meio fixo
- Um número de iterações fixa (10)
- Uso de IO (com ou sem)
- O número de passos para salvar o meio (fixar em algum valor arbitrário igual para todos)
- O número de replicações
- Tamanho da segmentação
- Tipo do escalonador
  |--------+----------------------------------------------------+-------------|
  | name   | descriptor                                         | performance |
  |--------+----------------------------------------------------+-------------|
  | eager  | queue central, não faz prefetch                    | no          |
  | random | random                                             | no          |
  | ws     | worker rouba a task de outro caso este esteja idle | no          |
  | lws    | tipo ws, mas local                                 | no          |
  | dm     | usa tempo de execução                              | yes         |
  | dmda   | tipo dm, mas conta com o tempo de transferência    | yes         |
  | dmdar  | tipo dmda, mas considera o local                   | yes         |

Não estamos incluindo outros escalonadores que levam em consideração a prioridade das tasks,
pois estes são desnecessários. O star-fletcher é dominado por uma única task.

** Experimento para determinar tamanho do bloco

#+BEGIN_SRC R :session *R* :async yes :results output silent 
  library(numbers)
  source("./libExp.R")

  #no scientific notation
  options(scipen = 999)


  total_width = 576
  border_size = 4
  absorb_size = 8
  width = total_width - 2 * (border_size + absorb_size)
  seed = 0
  time_step = 0.00001
  iterations = 20
  output = 5 # output every 5 steps
  replications = 5

  segmentations = divisors(total_width)

  cpu_factors <- list(
    WithIO =  c(0, 1),
    BlockSeg = segmentations[segmentations > 3 & segmentations < 48],
    Schedulers = c("lws", "dm", "dmda", "dmdar")
  )

  ex <- generate_experiment(cpu_factors, replications, seed) |>
    as_tibble() |>
    mutate(
  	Width = width,
  	AbsorbSize = absorb_size,
  	BorderSize = border_size,
  	TotalTime = format(time_step * iterations, scientific = FALSE),
  	TimeStep = format(time_step, scientific = FALSE),
  	OutputTime = format(time_step * output, scientific = FALSE)
    )


  #print(dim(ex))

  #ex |> readr::write_csv(glue("./ideal-seg/ideal-block-segment.csv"))

#+END_SRC


Obteve-se, a partir de um projeto experimental a parte, o arquivo =best-config.csv=, que entrega a melhor configuração por máquina
Essa configuração contém: Machine, BlockSize, TotalThreads, Msamples, ThreadX, ThreadY, ThreadZ
Msamples é redundante aqui.

Nota-se que a configuração é relativa a máquina em que está executando.
Nisso, gostaria também de extrair, qual das configurações por tamanho de bloco foi, num geral, melhor.

Isso eu preciso voltar nos dados anteriores e fazer talvez uma média dos Msamples ou algo tipo.


Uma dificuldade encontrada é que os tamanhos de bloco não geram um todo divisível.
No sentido que, o MMC deles não é um número viável para os experimentos.

#+BEGIN_SRC R :session *R* :async yes
  mLCM(c(32, 48, 64, 96, 128, 160))
#+END_SRC

#+RESULTS:
: 1920

Era desejado manter um volume total fixo e simplesmente ir alterando a granularidade dos blocos.
Isso não é possível com a configuração atual.
Porém, se o número maior (160) foi aumentado para 192, temos um número trabalhável.

#+BEGIN_SRC R :session *R* :async yes
  mLCM(c(32, 48, 64, 96, 128, 192))
#+END_SRC

#+RESULTS:
: 384

Podendo até multiplicar o resultado final por 2 caso necessário, vide que no maior tamanho de bloco,
haverá apenas 2^3 tasks, que pode afetar a execução.

#+BEGIN_SRC R :session *R* :async yes

  # fixing the best config table for latter merge
  best_config <- read_csv("./ideal-seg/best-config.csv") |>
    as_tibble() |>
    select(-Msamples) |>
    mutate(BlockSize = map_int(BlockSize, \(size) if (size == 160) 192 else size))


  block_sizes = unique(best_config$BlockSize)
  total_width = 2 * mLCM(block_sizes)
  border_size = 4
  absorb_size = 8
  width = total_width - 2 * (border_size + absorb_size)
  seed = 0
  time_step = 0.00001
  iterations = 20
  output = 5 # output every 5 steps
  replications = 6

  # Need to take the block size and calculate how many segmentations it can produce
  # use divisors
  # then build the experimental project and cross joint it in the for loop
  # making one project per machine

  kernel_factors <- list(
    WithIO =  c(0, 1),
    BlockSize = block_sizes,
    Schedulers = c("lws", "dm", "dmda", "dmdar")
  )


  ex_kernel_opt <- generate_experiment(kernel_factors, replications, seed) |> as_tibble()
    #mutate(BlockSize = as.integer(as.character(BlockSize))) |>
    #left_join(best_config, by = "BlockSize")



  machs <- best_config$Machine |> unique()

  for(m in machs){
  	values <- best_config |> filter(Machine == m)
          mach_name <- sub("\\d+$", "", m)

          res <- ex_kernel_opt |> 
            mutate(BlockSize = as.integer(as.character(BlockSize))) |>
            left_join(values, by = "BlockSize") |>
            mutate(
              BlockSeg = total_width / BlockSize,
              Blocks = sub("\\.", "", Blocks),
              Width = width,
              AbsorbSize = absorb_size,
              TotalTime = format(time_step * iterations, scientific = FALSE),
              TimeStep = format(time_step, scientific = FALSE),
              OutputTime = format(time_step * output, scientific = FALSE)
            ) |>
            select(-c(TotalThreads, Machine, BlockSize))
          
          
          res |> readr::write_csv(glue("./ideal-seg/from-kernel-exp-{mach_name}.csv"))
  }


#+END_SRC

#+RESULTS:
: ob_comint_async_R_file_/tmp/nix-shell.PWYpOg/babel-cvYsrv/R-DCRn1M


 
 
* Análise de Dados


Dados da execução inicial.

#+BEGIN_SRC R :session *R* :async yes :results output silent 
   options(crayon.enabled = FALSE)
   source("libExp.R")

   ex_star_fletcher <- read_csv('./ideal-seg/ideal-block-segment.csv')
   ex_fletcher_base <- read_csv('./ideal-seg/base-test.csv')

   sf <- machines |> cross_join(ex_star_fletcher)
   fb <- machines |> cross_join(ex_fletcher_base)

   sf_res <- sf |>
     mutate(
       Order = (Width + 2 * (AbsorbSize + BorderSize)) / BlockSeg,
       FILE = paste0(base_dir,"/ideal-block-size-machine/", Machine ,"/stdout-", Schedulers, "-", BlockSeg, "-", WithIO, "-", substring(1, Blocks), ".out")) |>
     parse_files(FILE, function(lines){
       msamples <-  lines |> str_subset("Msamples/s") |> str_extract("\\d+.\\d+") |> as.numeric()
       exec_time <-  lines |> str_subset("Computation Elapsed time") |> str_extract("\\d+.\\d+") |> as.numeric()
       tribble(~Msamples, ~ExecTime,
               msamples[1], exec_time[1])
     })

  fb_res <- fb |>
    mutate(FILE = paste0(base_dir,"/fletcher-base-max-size/", Machine ,"/stdout-",  WithIO, "-", substring(1, Blocks), ".out")) |>
     parse_files(FILE, function(lines){
       msamples <-  lines |> str_subset("MSamples/s") |> str_extract("\\d+.\\d+") |> as.numeric()
       exec_time <-  lines |> str_subset("Total execution time") |> str_extract("\\d+.\\d+") |> as.numeric()
       tribble(~Msamples, ~ExecTime,
               msamples[1], exec_time[1])
     })
#+END_SRC

#+BEGIN_SRC R :session *R* :async yes

    plot_msamples <- function(io_state){
      x_breaks <- sort(unique(sf_res$Order))

      max_fb <- fb_res |>
  	filter(WithIO == io_state) |>
  	group_by(Processor) |>
  	summarize(Max_Msamples = max(Msamples, na.rm = TRUE), Min_Msamples = min(Msamples, na.rm = TRUE), .groups = "drop") #|>
  	# Join back to machines so the hline can inherit the exact Machine color
  	#left_join(machines |> select(Machine, Processor), by = "Processor")
      
      ggplot(sf_res |> filter(WithIO == io_state) |> filter(Schedulers == "dmdar" | Schedulers == "lws"), aes(x = Order, y = Msamples, color = Processor)) +
      geom_jitter(width = 2, alpha = 0.3) +
      geom_hline(data = max_fb, aes(yintercept = Max_Msamples, color = Processor), linetype = "dashed", linewidth = 0.8) +
      #geom_hline(yintercept = max_samples, color = "red", linewidth = 0.5) +
      scale_x_continuous(breaks = x_breaks) +
      #scale_y_continuous(trans='log2') +
      ylim(0,NA)+
      facet_grid(~ Schedulers) + 
      labs(
  	title = paste0("Msamples vs. Block Order when WithIO = ", io_state),
  	subtitle = "Faceted by Scheduler",
  	x = "Block Size",
  	y = "Msamples/s"
      ) +
      theme_bw(base_size=15) +
      theme(legend.position = "bottom")
  }

    #plot_msamples(0) / plot_msamples(1)
  plot_msamples(0)
      
#+END_SRC

#+RESULTS:
