* Plano do Projeto Experimental

Agora precisamos verificar qual a melhor configuração de dados para o kernel atual.
Quantos blocos e treads.
Com esse experimentos, a cada otimização, podemos verificar se ela foi efeitiva.


** Máquinas

Quais máquinas iremos executar?

| Máquina | Nº GPUS | Local         |
|---------|---------|---------------|
| grace   |       1 | PCAD          |
| cidia   |       2 | PCAD          |
| tupi    |       1 | PCAD          |
| poti    |       1 | PCAD          |
| saude   |       3 | PCAD          |


O plano é executar experimentos em todas essas máquinas.

** Parâmetros

Quais parâmetros queremos analisar nos testes.
Temos as dimensões do bloco, e como distribuir elas.
Por exemplo, com um bloco de 8 x 8 x 8, temos 512 threads por bloco.
Se reduzissemos para 8 x 8 x 4, teríamos 256 threads por bloco, mas mais blocos.
Na nossa análise, idealmente fixariamos o tamanho dos /fletcher-blocks/ e só alteriariamos dentro do CUDA.
Acho que isso não é possível pois muda muito quantos /CUDA-blocks/ ocorrem por execução, o que afeta o resultado.
Assim, precisamos manter um número de /fletcher-blocks/ baixo, vide que essa métrica não é tão relevante,
mas alteramos o tamanho deles e mexemos na distribuição e quantidade de threads.
Selecionamos sets de threads, 1024, 512, 256, 128, 64 e para cada um deles, geramos uma configuração de bloco.

O número de iterações será sempre fixo.

Preciso ainda instrumentar a leitura desses parâmetros no código fonte.

** Hipóteses

Imagina-se que alguma das configurações usadas será a ideal.
Minha hipótese atual é que os valores ótimos estarão com um /fletcher-block/ grande.
Além disso, uma distribuição igual de threads por dimensão provavelmente trará o melhor resultado.


** Experimentos

#+BEGIN_SRC R :session *R* :async yes :results output silent 
     library(DoE.base)
     library(glue)
     library(tidyverse)
     library(numbers)
  library(purrr)

     #no scientific notation
     options(scipen = 999)

     num_of_blocks = 3
     iterations = 10
     seed = 0
     replications = 5

     generate_experiment <- function(factors, replications, seed) {
       DoE.base::fac.design(
         nfactors = length(factors),
         replications = replications,
         repeat.only = FALSE,
         randomize = TRUE,
         seed = seed,
         nlevels = sapply(factors, length),
         factor.names = factors
       )
     }

    # quebra o número de threads em suas possíveis fatorações
   fatoracoes3 <- function(n) {
     resultados <- list()
     for (a in 1:round(n^(1/3))) {
       if (n %% a == 0) {
         resto1 <- n %/% a
         for (b in a:floor(sqrt(resto1))) {
           if (resto1 %% b == 0) {
             c <- resto1 %/% b
             if (c >= b) {
               resultados[[length(resultados) + 1]] <- c(c, b, a)
             }
           }
         }
       }
     }
     resultados
   }

    amount_threads <- c(64, 128, 256, 512)

    not_half <- \(v) v[[1]] < 2 * (v[[2]] + v[[3]])
   
    factors <- list(
      ThreadConfig = amount_threads |>
        map(\(x) Filter(\(y) map(y, log2) |> not_half(), fatoracoes3(x)) |> map_chr(\(l) paste(l, collapse = " "))) |>
        list_c() |>
        unique(), 
      BlockSize = c(32, 48, 64, 96, 128, 160)
    )


    factors_full <- list(
      ThreadConfig = amount_threads |>
        map(\(x) fatoracoes3(x) |> map_chr(\(l) paste(l, collapse = " "))) |>
        list_c() |>
        unique(), 
      BlockSize = c(32, 48, 64, 96, 128, 160)
    )

  mk_exp <- function(f) {
    generate_experiment(f, replications, seed) |> as_tibble() |>
      mutate(
    	BlockCount = num_of_blocks,
    	Iterations = iterations,
        ThreadConfig = as.character(ThreadConfig),
        Blocks = str_sub(Blocks, 2, 2)
      ) |>
       separate_wider_delim(
  	ThreadConfig,
  	delim = " ",
  	names = c("ThreadX", "ThreadY", "ThreadZ"),
  	cols_remove = TRUE   # set FALSE if you want to keep the original combined column too
    ) |>
    mutate(
      across(c(ThreadX, ThreadY, ThreadZ), as.integer),
      TotalThreads = ThreadX * ThreadY * ThreadZ
    )

  }
  k_ex <- mk_exp(factors)
  k_ex |> readr::write_csv(glue("./kernel-analysis/kernel-params.csv"))


  kfull_ex <- mk_exp(factors_full)
  kfull_ex |> readr::write_csv("./kernel-analysis/kernel-params-full.csv")
   
#+END_SRC

** Possibilidades de otimização

O tabalho do fletcher dos outros labs usa uma configuração de threads (32, 16, 1), com cada kernel da GPU
computando sobre o eixo z. Ou seja, tem um for loop sobre z ali dentro. Podemos implementar isso,
faremos uma branch separada e adicionaremos ela no flake propriamente anotada.


* Análise de dados


#+BEGIN_SRC R :session *R* :async yes :results output silent :exports none
  options(crayon.enabled = FALSE)
  #library(starvz)
  library(tidyverse)
  library(ggplot2)
  library(dplyr)
  library(patchwork)

  base_dir = "./kernel-analysis/results"

  machines <- tribble(
    ~Machine, ~Processor, ~Ghz, ~Threads, ~Cores, 
    "tupi3", "Intel(R) Core(TM) i9-14900KF", 3.2, 32, 24,
    "tupi4", "Intel(R) Core(TM) i9-14900KF", 3.2, 32, 24,
    "tupi5", "Intel(R) Core(TM) i9-14900KF", 3.2, 32, 24,
    "poti1", "Intel(R) Core(TM) i7-14700KF", 3.4, 28, 20,
    "poti3", "Intel(R) Core(TM) i7-14700KF", 3.4, 28, 20,
    "poti4", "Intel(R) Core(TM) i7-14700KF", 3.4, 28, 20,
    "poti5", "Intel(R) Core(TM) i7-14700KF", 3.4, 28, 20,
    "grace1", "2 x Grace A02", 3.4, 144, 144,
    "cei1", "2 x Intel(R) Xeon(R) Silver 4116", 2.1, 48, 24,
    "cei2", "2 x Intel(R) Xeon(R) Silver 4116", 2.1, 48, 24,
    "cei3", "2 x Intel(R) Xeon(R) Silver 4116", 2.1, 48, 24,
    "draco1", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16,
    "draco2", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16,
    "draco6", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16,
    "draco7", "2 x Intel(R) Xeon(R) E5-2640 v2", 2.0, 32, 16,
    "cidia", "2 x Intel(R) Xeon(R) Silver 4208", 2.1, 32, 16
  )

  parse_files <- function(tibble, FILE, parse_fn){
    mutate(tibble, Data = map( {{ FILE }} , function(file) {
      if(!dir.exists(dirname(file))){
        return(NULL)
      }
      #print(file)
      lines <- tryCatch({
        read_lines(file)
      }, error = function(e){
        message(paste0("Warning: Failed to read file: ", file, ". Skipping..."))
        return(NULL) # Returns NULL instead of breaking the script
      })
      if(is.null(lines)) {
        return(NULL)
      }
      parse_fn(lines)
    })) |>
    filter(lengths(Data) > 0) |>
    unnest(Data)
  }
#+END_SRC


#+BEGIN_SRC R :session *R* :async yes :results output silent :exports none
  kernel_exp <- read_csv('./kernel-analysis/kernel-params.csv')
  k <- machines |> cross_join(kernel_exp)

  k_res <- k |>
    mutate(FILE = paste0(base_dir,"/fletcher-kernel-analysis/", Machine ,"/stdout-", ThreadX, "-", ThreadY, "-", ThreadZ, "-", BlockSize, "-", Blocks, ".out")) |>
    parse_files(FILE, \(lines){
      vals <- lines |>  map(\(l) as.numeric(str_extract(l, " \\d+.\\d+")))
      tribble(~Msamples, ~ExecTime, 
              vals[[15]], vals[[14]])
    }) 

  kernel_exp_full <- read_csv('./kernel-analysis/kernel-params-full.csv')

  kfull_res <- machines |>
    cross_join(kernel_exp_full) |>
    mutate(FILE = paste0(base_dir,"/fletcher-kernel-analysis/", Machine ,"/stdout-", ThreadX, "-", ThreadY, "-", ThreadZ, "-", BlockSize, "-", Blocks, ".out")) |>
    parse_files(FILE, \(lines){
      vals <- lines |>  map(\(l) as.numeric(str_extract(l, " \\d+.\\d+")))
      tribble(~Msamples, ~ExecTime, 
              vals[[15]], vals[[14]])
    }) 


#+END_SRC

Encontar quais as 3 melhores configurações de threads para cada bloco

#+BEGIN_SRC R :session *R* :async yes 

  best_perf <- kfull_res |>
    mutate(ThreadName = paste0(ThreadX, "-", ThreadY, "-", ThreadZ)) |>
    arrange(desc(Msamples)) |>
    distinct(Machine, BlockSize, ThreadName, .keep_all = TRUE) |>
    group_by(Machine, BlockSize) |>
    slice_head(n = 3) |>
    select(Machine, BlockSize, TotalThreads, Msamples, ThreadX, ThreadY, ThreadZ) |>
    readr::write_csv(paste0("./kernel-analysis/best-config.csv"))


#+END_SRC


#+BEGIN_SRC R :session *R* :async yes :results output silent

  msamples_plot <- function(kt) {
    kt_msamples_plot <- kt |>
      select(-FILE) |>
      mutate(
        #Machine = str_sub(Machine, end = -2),
        ThreadName = paste0(ThreadX, "-", ThreadY, "-", ThreadZ),
        ThreadName = factor(
          ThreadName,
          levels = unique(ThreadName[order(ThreadZ, ThreadY, ThreadX)])
        )
      )
     # group_by(across(-c(Msamples, ExecTime, Blocks))) |>
     # summarize(
     #   rep = n(),

    #   Msamples_mean = mean(Msamples),
    #   Msamples_sd = sd(Msamples),
    #   Msamples_error = (3 * Msamples_sd) / sqrt(rep),
    #   
    #   ExecTime_mean = mean(ExecTime),
    #   ExecTime_sd = sd(ExecTime),
    #   ExecTime_error = (3 * ExecTime_sd) / sqrt(rep),
    #   .groups = "drop"
    # ) 

    ggplot(kt_msamples_plot, aes(x = ThreadName, y = Msamples, color = factor(BlockSize))) +
      #geom_point(alpha = 0.8) +
      geom_jitter(alpha = 0.8, width = 0.1) +
      #geom_errorbar(aes(ymin = Msamples_mean - Msamples_error, ymax = Msamples_mean + Msamples_error, color = Machine), width = 0.5) +
     # scale_x_continuous(breaks = x_breaks) +
      ylim(0, NA) +
      facet_grid(Machine ~ TotalThreads,  scales = "free", space = "free_x") + #, scales = "free_y") + 
      labs(
    	title = paste0("MSamples vs. Block Order"),
    	subtitle = "Faceted by Scheduler (X axis) and Machine (Y axis)",
    	x = "Block Size",
    	y = "Msamples/s"
      ) +
      theme_bw(base_size = 15) +
      theme(legend.position = "bottom")
  }

  msamples_plot(kfull_res)

#+END_SRC


** Hipóteses

+ Fazer o fine tunning da chamada do kernel não afeta o resultado do StarPU 
  - When Faster Kernels Do Not Mean Faster Applications in Exascale GPU Systems [[https://easychair.org/smart-program/Euro-Par2026/2026-08-27.html#talk:320098][abstract]].
  - Quanto que isso afeta
    - Observar as curvas dos kernel experimentais (no fine tunning)
    - Verificar se o StarFletcher acompanha a curva

+ O fine tunning é favorável a dimensão que cresce mais devagar, com a melhor configuração distribuindo
  melhor as threads nas dimensões X e Y.
  - Isso resulta em um resultado superior no StarFletcher
